config:
  google:
    client-id: xxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
    client-secret: xxxxxxxxxxxxxxxxxxx
    scope: openid email profile
    server_metadata_url: https://accounts.google.com/.well-known/openid-configuration
  storage:
    secret: my secret
  logging:
    format: "%(asctime)s - %(levelname)s - %(message)s"
  ui:
    host: localhost
    reload: False
    reconnect_timeout: 10.0
    uvicorn_reload_includes: "*.py, *.css, *.html"
