name: Docker Build and Push

on:
  push:
    branches: ["main"] # Trigger on pushes to the main branch
  pull_request:
    branches: ["main"] # Trigger on pull requests targeting the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Required for pushing to GHCR

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        if: github.event_name == 'push' # Only login on push events
        run: |
          # echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          # For GitHub Container Registry (GHCR):
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and Push Docker Image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' }} # Only push on push events
          # dockerhub-username/my-basket:latest # Replace with your Docker Hub username and image name
          # dockerhub-username/my-basket:${{ github.sha }}
          # For GitHub Container Registry (GHCR):
          tags: |
            ghcr.io/${{ github.repository }}/my-basket:latest
            ghcr.io/${{ github.repository }}/my-basket:${{ github.sha }}
          build-args:
            # Add any build arguments your Dockerfile needs
            # VERSION: ${{ github.run_id }}
